### ISSUE TITLE
possibility to add patterns for known issues

### ISSUE THREAD

**Issue by chaws** [Linaro/qa-reports-known-issues#143]
This was brought up by @nareshkamboju :

for example, we could have known issue described like this
```yaml
test_names:
  - */quotactl01
```

instead of this (currently):
```yaml
test_names:
  - ltp-syscalls-tests/quotactl01
  - ltp-syscalls-kasan-tests/quotactl01
  - ltp-syscalls-compat-tests/quotactl01
  - ltp-syscalls-64k-page_size-tests/quotactl01
```

**Comment by roxell** [comment]
what happens if we have the same name in kselftest and ltp, and its only the kselftest test that is flaky... can I do something like this:
- kselftest*/quotactl01

**Comment by chaws** [comment]
This is being possible right now
